name: Flask Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Start Flask server
        run: python server.py &

      - name: Wait for server to start
        run: sleep 5

      - name: Check if server is running
        run: |
          if curl --head --fail http://localhost:5000; then
            echo "Server started successfully"
            exit 0
          else
            echo "Server failed to start"
            exit 1
          fi
